name: ibooking
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  http: ^0.13.6
  google_maps_flutter: ^2.2.5
  shared_preferences: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/bangunan.jpg
    - assets/bangunan1.jpg
    - assets/perkeso.png
    - assets/profile.png
    - assets/vehicle1.jpg
